# Generated by Django 3.2 on 2021-05-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='grp_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.groupthread'),
        ),
    ]
