# Generated by Django 3.2 on 2021-04-25 15:20

from django.db import migrations
import user.managers.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.user.UserManager()),
            ],
        ),
    ]
