# Generated by Django 3.2 on 2021-05-04 12:00

from django.db import migrations, models
import django.utils.timezone
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user.upload_dp),
        ),
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
